### ISSUE TITLE
Add a new sensor after the default ones isn't working

### ISSUE THREAD

**Issue by Pulpyyyy** [kamaradclimber/rte-ecowatt#19]
Hello,

After installing the default sensors, it is not possible to add a new one (ex day+2)
Using UI, it seems fine but the sensor is not created.
![ecowatt](https://user-images.githubusercontent.com/32004297/194912219-f0877984-0883-4581-a6c1-fbc45c51082f.gif)

**Comment by kamaradclimber** [comment]
Indeed, at the moment you need to remove and then re-add the integration. I'll try to add this next weekend.

**Comment by kamaradclimber** [comment]
Version 0.3.0 (pre-release for now) has a way to add more sensors. I could not find a way to delete existing sensors using this mechanism. Let me know if there are still issues and I'll reopen this issue.

**Comment by Pulpyyyy** [comment]
Adding a new sensor is ok, maybe just missing a reload/refresh to update the sensor count
Thanks

**Comment by kamaradclimber** [comment]
It's working on my demo instance. Could you set `custom_components.rte_ecowatt: debug` logger config and send me the output? (take care of removing your credentials if they appear).

**Comment by Pulpyyyy** [comment]
Either I messed up my setting or debugging doesn't provide output.
![ecowatt](https://user-images.githubusercontent.com/32004297/196044503-02afe739-3424-4354-9fc6-2c6cd319525e.gif)
