### ISSUE TITLE
Ecogaz disponible

### ISSUE THREAD

**Issue by Gus1994** [kamaradclimber/rte-ecowatt#22]
Bonjour, petit post pour vous informer que Ecogaz est désormais disponible: https://myecogaz.com/home

**Comment by Gus1994** [comment]
https://odre.opendatasoft.com/explore/dataset/signal-ecogaz/information/

**Comment by kamaradclimber** [comment]
Merci! J´ai vu le [thread](https://forum.hacf.fr/t/api-ecogaz/16865) et vais le suivre. Je vais laisser un autre volontaire implémenter une intégration (je n'en ai que très peu besoin).

**Comment by kamaradclimber** [comment]
En fait j'ai bricolé une demo: https://github.com/kamaradclimber/signal_ecogaz
