### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by Sonic62** [kamaradclimber/rte-ecowatt#23]
Hello

Seconde erreur 

```Logger: homeassistant
Source: custom_components/rte_ecowatt/__init__.py:356
Integration: My EcoWatt by RTE ([documentation](https://github.com/kamaradclimber/rte-ecowatt), [issues](https://github.com/kamaradclimber/rte-ecowatt/issues))
First occurred: 22:40:05 (2 occurrences)
Last logged: 22:56:05

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/rte_ecowatt/__init__.py", line 332, in _find_ecowatt_level
    ecowatt_data = next(
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/config/custom_components/rte_ecowatt/__init__.py", line 265, in _handle_coordinator_update
    ecowatt_level = self._find_ecowatt_level()
  File "/config/custom_components/rte_ecowatt/__init__.py", line 356, in _find_ecowatt_level
    raise RuntimeError(
RuntimeError: Unable to find ecowatt level for 2022-11-05 21:40:05.239338+01:00 (hour shift: 23)```

**Comment by Sonic62** [comment]
> Hello
> 
> Seconde erreur
> 
> `Logger: homeassistant Source: custom_components/rte_ecowatt/**init**.py:356 Integration: My EcoWatt by RTE ([documentation](https://github.com/kamaradclimber/rte-ecowatt), [issues](https://github.com/kamaradclimber/rte-ecowatt/issues)) First occurred: 22:40:05 (2 occurrences) Last logged: 22:56:05
> 
> Error doing job: Task exception was never retrieved Traceback (most recent call last): File "/config/custom_components/rte_ecowatt/**init**.py", line 332, in _find_ecowatt_level ecowatt_data = next( StopIteration
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval await self._async_refresh(log_failures=True, scheduled=True) File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh self.async_update_listeners() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners update_callback() File "/config/custom_components/rte_ecowatt/**init**.py", line 265, in _handle_coordinator_update ecowatt_level = self._find_ecowatt_level() File "/config/custom_components/rte_ecowatt/**init**.py", line 356, in _find_ecowatt_level raise RuntimeError( RuntimeError: Unable to find ecowatt level for 2022-11-05 21:40:05.239338+01:00 (hour shift: 23)`

**Comment by kamaradclimber** [comment]
Merci d'avoir rapporté ce bug. 
Je soupconne qu'il arrive pour le sensor le plus loin dans le futur uniquement, au moment du changement de jour (aux alentours de minuit heure locale)
Pouvez vous confirmer?

**Comment by Sonic62** [comment]
Hello

J'ai fait un reboot electrique de HA , et je l'ai laissé tranquille pendant quelques heures..
J'ai recupere le fichier .log de HA, c'est aleatoire 
[nouveau 2.txt](https://github.com/kamaradclimber/rte-ecowatt/files/9929540/nouveau.2.txt)

**Comment by kamaradclimber** [comment]
Bonjour,

je pense que le problème est maintenant corrigé (avec la version 0.6.3).
Je ferme le ticket mais pas de pb pour le ré-ouvrir si nécessaire.
