### ISSUE TITLE
No configuration UI

### ISSUE THREAD

**Issue by Kriss1670** [kamaradclimber/rte-ecowatt#26]
I have no way to configure the API, i.e. giving my client id and secret id.
![Capture d’écran 2022-11-24 182202](https://user-images.githubusercontent.com/80743001/203839646-e328603e-9592-4add-811c-c83c2f4ea612.jpg)

**Comment by kamaradclimber** [comment]
Hello,

the integration is configured similarly to all integration in Home Assistant: Settings->Devices & Services -> Add Integration

![image](https://user-images.githubusercontent.com/503537/203843661-237d1111-640c-4a5f-a453-5e104abd0653.png)
![image](https://user-images.githubusercontent.com/503537/203843682-d5873f67-5e46-4dc1-817b-d90674779bfb.png)
![2022-11-24-185159_555x438_scrot](https://user-images.githubusercontent.com/503537/203843773-ac1f8ad1-ed7c-4677-8230-fafe8cdc2317.png)

**Comment by Kriss1670** [comment]
I’ve done this and I don’t have any problem to install the integration. But as my screenshot shows, after installing, I don’t have the window to enter my client id and secret.

**Comment by kamaradclimber** [comment]
Either we don't understand each other or there is a bug in the integration (or HA) indeed.

Let's go through in details:
- could you show me a screenshot of your "Devices & Services" page showing the rte-ecowatt integration added. See the example on my installation ![2022-11-25-084025_767x267_scrot](https://user-images.githubusercontent.com/503537/203926974-64ce6bd7-3f45-4b91-accb-521e58913938.png)
- could you look at your home-assistant.log and tell me if there are any error when you add the integration? Does those logs happen also during a HA restart?

**Comment by Kriss1670** [comment]
Ok, I got it !
I didn’t get that after installing the HACS integration I also needed to add the integration from « Devices and services »… I don’t think this is stated in the help and never had this kind of « double step » integration install. Sorry for that. I now have the configuration pop up to enter my credentials.
Thanks for help !

**Comment by kamaradclimber** [comment]
I'm glad we found it then :)
This is normally pretty standard way for 3rd party integration, although it can be more obvious when the integration makes automatic discovery.
