### ISSUE TITLE
Valeurs possibles

### ISSUE THREAD

**Issue by Bastiencc** [kamaradclimber/rte-ecowatt#37]
Bonjour

Merci pour le travail !
Question : quelles sont les différentes valeurs possibles pour les sensors?

merci !

**Comment by Bastiencc** [comment]
merci!

**Comment by Bastiencc** [comment]
C'est normal de ne pas avoir de valeur sur certains sensor?

![image](https://user-images.githubusercontent.com/37021892/206922148-e8571020-fa6d-4dd5-ad8b-8723faac68d5.png)

**Comment by kamaradclimber** [comment]
Elles apparaissent au rafraichissement suivant (au bout de ~15minutes)

**Comment by kamaradclimber** [comment]
Ca ressemble à #28 alors

**Comment by Bastiencc** [comment]
Merci. Je regarde ça demain et je ferai un retour, bonne soirée !

Le dim. 11 déc. 2022 à 20:21, Grégoire Seux ***@***.***> a
écrit :

**Comment by Bastiencc** [comment]
Effectivement c'est ça. J'ai refait l'installation depuis le début en
utilisant en premier lieu les sensor par défaut et tout est ok désormais.
Merci!

Le dim. 11 déc. 2022 à 20:25, Bastien Huneau ***@***.***> a
écrit :
