### ISSUE TITLE
Uniformisation des noms de calendrier

### ISSUE THREAD

**Issue by Pulpyyyy** [kamaradclimber/rte-ecowatt#38]
Salut,
Sur la version 0.6.0 les calendriers se créent bien
![image](https://user-images.githubusercontent.com/32004297/206923677-33c27b7c-8886-4eff-981f-af9ba4426835.png)
et 
![image](https://user-images.githubusercontent.com/32004297/206923693-9e69bd81-38e6-4b60-9032-9b1e4807d207.png)
Par contre, est-ce utile d'appeler le premier avec calendar à la fin  `calendar.ecowatt_downgraded_level_calendar` ? Si oui alors il faut faire pareil sur le deuxième
@++

**Comment by kamaradclimber** [comment]
Bien vu, merci
