### ISSUE TITLE
Need a device to group ecowatt entities

### ISSUE THREAD

**Issue by Pulpyyyy** [kamaradclimber/rte-ecowatt#44]
Salut @kamaradclimber 

Sur la version 0.6.3  la vue appareil est vide :
![image](https://user-images.githubusercontent.com/32004297/207668564-45cfe824-7ba7-457b-a131-38b56969418d.png)
Pourtant les entités sont là :
![image](https://user-images.githubusercontent.com/32004297/207668658-64f26f43-46e4-4097-8510-28bce6aeddf4.png)
Et valorisées : 
![image](https://user-images.githubusercontent.com/32004297/207668833-4064d3c3-e9de-49c2-90de-7da918b12013.png)

@+

**Comment by kamaradclimber** [comment]
C'est normal, je n'ai ajouté un device que pour les entité venant d'Enedis et tu ne les pas activées (je pense).

**Comment by Pulpyyyy** [comment]
Oui, je ne m'attendais à pas à voir les entités Enedis, mais bien celles d'ecowatt.
Après si effectivement tu n'as pas prévu un appareil pour les regrouper, alors c'est pas une issue
Merci à toi
