### ISSUE TITLE
Repository kamaradclimber/rte-ecowatt not found

### ISSUE THREAD

**Issue by thibautd88** [kamaradclimber/rte-ecowatt#5]
Hello,

Tout d'abord merci énormément pour ce partage !
Je n'arrive pas à trouver l'integration sous HACS que ce soit par le lien ou en recherchant manuellement.
Repository kamaradclimber/rte-ecowatt not found

**Comment by kamaradclimber** [comment]
Normalement il faut ajouter le repository en tant que "custom repository". Voilà quelques captures d'écran:

![image](https://user-images.githubusercontent.com/503537/193544941-9734420f-4442-43b4-9856-da5a72753390.png)

![image](https://user-images.githubusercontent.com/503537/193545051-16109fbc-48c2-43b7-b992-d589929c214e.png)

**Comment by thibautd88** [comment]
It works !! Thanks a lot !
