### ISSUE TITLE
can't restart HA after new release

### ISSUE THREAD

**Issue by StephaneRod** [kamaradclimber/rte-ecowatt#51]
After having loaded the last version of today 16/12/2022
HA can't restart and I have got this message when checking the config :
Invalid config for [sensor.rte_ecowatt]: required key not provided @ data['enedis_load_shedding']. Got None. (See ?, line ?).

any idea ?

**Comment by giacinti** [comment]
Same issue here.
I could fix it in removing my rte_ecowatt config yaml file and go through the ui configuration (i.e. add a new integration, config etc...)
