### ISSUE TITLE
How present data in dashboard

### ISSUE THREAD

**Issue by binerf** [kamaradclimber/rte-ecowatt#52]
Hi,

Many thanks for this extension !!

I'm wondering what is the best presentation to integrate data in HA dashboard ?

Could you share some examples of dashboard integration please ?

Thank you !

**Comment by kamaradclimber** [comment]
I think it would better to read https://forum.hacf.fr/t/api-ecowatt/15451 (in :fr: ) and ask there. I'm using the default auto-generated dashboard of HA.
