### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by Yoanf26** [kamaradclimber/rte-ecowatt#53]
Bonjour

C'est encore moi. Cela fait deux nuits de suite où j'ai cette erreur qui apparaît.

Logger: homeassistant
Source: custom_components/rte_ecowatt/__init__.py:483
Integration: My EcoWatt by RTE ([documentation](https://github.com/kamaradclimber/rte-ecowatt), [issues](https://github.com/kamaradclimber/rte-ecowatt/issues))
First occurred: 00:02:33 (1 occurrences)
Last logged: 00:02:33

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/rte_ecowatt/__init__.py", line 463, in _find_ecowatt_level
    ecowatt_data = next(
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 316, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 121, in async_update_listeners
    update_callback()
  File "/config/custom_components/rte_ecowatt/__init__.py", line 348, in _handle_coordinator_update
    ecowatt_level = self._find_ecowatt_level()
  File "/config/custom_components/rte_ecowatt/__init__.py", line 483, in _find_ecowatt_level
    raise RuntimeError(
RuntimeError: Unable to find ecowatt level for 2022-12-28

J'ai comme l'impression que le J+3 pose problème. Pourtant jusqu'au 23 décembre, je n'avais aucune erreur.

**Comment by kamaradclimber** [comment]
Bonjour,
On peut imaginer que RTE ne publie pas les information avec suffisament d'avance pour que le J+3 fonctionne systémtiquement. Il me semble que les infos du J+3 sont publiées tôt le matin et non pas à minuit. 
Il faut que je réflechisse pour trouver le comportement approprié.

**Comment by Yoanf26** [comment]
Bonjour,

Si ce n'est que ça, ce n'est pas gênant car j'ai bien l'impression que l'info est bien remonté plus tard. Mais il est vrai que j'ai passé une période où j'ai contrôlé un peu tous les défauts (et j'en avais pas mal suite à mes sensors persos vis à vis de mon serveur Nas).

**Comment by jerome6994** [comment]
Bonjour,

le sujet est toujours d'actualité, existe il une solution pour corriger l'erreur à faire en local ?

Merci pour le travail en tout cas

**Comment by kamaradclimber** [comment]
Bonjour @jerome6994 ,

aucune solution pour le moment, il faudrait probablement trouver l'heure de publication habituelle et ne regarder J+3 qu'à partir de cette heure. Je suis preneur d'un patch si quelqu'un veut essayer!

**Comment by kamaradclimber** [comment]
Ma proposition est de placer le sensor J+3 en état inconnu (None) lorsque l'info n'est pas disponible, avec un log en niveau info.
L'utilisation du niveau ecowatt J+3 est:
- soit informative (dans ce cas, on peut tout à fait tolérer que le capteur n'affiche aucune info entre minuit et ~7h du matin)
- soit réservée à des utilisations avancées (commencer à monter le niveau de chauffage en prévision d'un jour rouge où le chauffage sera fortement réduit ?) qui de toute façon auront besoin de prendre en compte les niveaux J+1 et J+2 également donc écrire du code assez smart.

**Comment by kamaradclimber** [comment]
Example: 
![image](https://github.com/kamaradclimber/rte-ecowatt/assets/503537/2dfed2ae-46d1-4ec4-9184-5c8db1338cfc)

**Comment by jerome6994** [comment]
Bonjour

Je ne sais pas qui utilise l'info à J+3 et surtout considère ceci fiable à 100% !
Pour le chauffage c'est pas au jour le jour mais pas loin quand même donc oui il y aura contrôle du J+1 voir J+2.

Plutôt qu'afficher None cela peut être :

- Situation normal, etc...
- Non diffusé (ou dans le genre)
- None si c'est vraiment planté 

Après je ne connais pas les différents cas possible comment cela remonte etc..
Je suis un peu un quiche en programmation :)
