### ISSUE TITLE
Impossibilité de configurer un nouveau capteur (granularité journalière)

### ISSUE THREAD

**Issue by laurentchivot** [kamaradclimber/rte-ecowatt#54]
Les capteurs par défaut (now et today) sont bien renseignés, 2 nouveaux capteurs (tomorrow et 2 days) ne sont jamais mis à jour (valeur : Inconnu).

Un redémarrage de HA ne change rien.

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:520
Integration: Capteur ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 14:05:45 (1 occurrences)
Last logged: 14:05:45
Platform rte_ecowatt does not generate unique IDs. ID ecowatt-level-in-1-days already exists - ignoring sensor.ecowatt_level_tomorrow

**Comment by kamaradclimber** [comment]
HA a l´air de considérer que les capteurs existent déjà. Je suggère de les supprimer, de redémarrer HA et ensuite de les re-rajouter.

**Comment by laurentchivot** [comment]
C'est là que çà se complique ;-), 
Lorsque je cherche à supprimer les 2  entités en question (tomorrow et 2 days)
j'ai le message : 
Vous ne pouvez supprimer que 0 des 1 entités sélectionnées. Les entités ne peuvent être supprimées que si leur intégration ne les fournit plus. Vous devez parfois redémarrer Home Assistant avant de pouvoir supprimer les entités d'une intégration supprimée. Voulez-vous vraiment supprimer les entités pouvant l'être ?

dois je passer par la supression de l'intégration elle même ?

Merci

Laurent

**Comment by Yoanf26** [comment]
Hello

J'avais eu ce bug.

J'avais supprimé l'intégration avec un double redémarrage. Puis ajout de l'intégration, redémarrage, attente de 16 minutes pour être sûr que les entités de base soient bien pris en compte, puis je fais un ajout, redémarrage et attente de 16 minutes pour être sûr que la nouvelle entité soit pris en compte et ainsi de suite.

**Comment by laurentchivot** [comment]
Merci @Yoanf26 , j'applique votre méthode et je reviens clore l'issue si tout s'est bien passé.
16 minutes ...parce que c'est le timer d'interrogation de la plateforme RTE ;-) je suppose ?

**Comment by Yoanf26** [comment]
Il me semble que c'est pour ça.

**Comment by laurentchivot** [comment]
@kamaradclimber , je clos l'issue, la méthode proposée par @Yoanf26 a fonctionné

**Comment by Yoanf26** [comment]
Cool que cela a fonctionné chez toi
