### ISSUE TITLE
Problème avec 2023.2

### ISSUE THREAD

**Issue by epenet** [kamaradclimber/rte-ecowatt#56]
`Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for rte_ecowatt using this method at custom_components/rte_ecowatt/__init__.py, line 65: hass.config_entries.async_setup_platforms(`

Voir https://github.com/hacs/integration/pull/3038

**Comment by kamaradclimber** [comment]
Thanks for the report
