### ISSUE TITLE
Support api v5

### ISSUE THREAD

**Issue by kamaradclimber** [kamaradclimber/rte-ecowatt#68]
https://data.rte-france.com/catalog/-/api/doc/user-guide/Ecowatt/5.0 has been published on Nov 7th.
It is the likely cause of #67

**Comment by loicdeschamps** [comment]
merci, en attente d'un update cote HA qui  ne voie que la version 0.6.9 pour le moment

**Comment by kamaradclimber** [comment]
Effectivement hacs avait du mal à voir la mise à jour jusqu'à ce que je clique sur "update information"
![image](https://github.com/kamaradclimber/rte-ecowatt/assets/503537/72d41f39-239f-4dd5-8f47-f29e0757a6eb)
