### ISSUE TITLE
indicateur  « Heures décarbonées » 

### ISSUE THREAD

**Issue by algernon2607** [kamaradclimber/rte-ecowatt#78]
Bonjour

Est il prévu que l’intégration fournisse les nouveaux indicateurs fournis avec la version 5 de l'API Ecowatt ?

Cordialement

**Comment by kamaradclimber** [comment]
Bonjour, 
en théorie, c'est déjà le cas (cf https://github.com/kamaradclimber/rte-ecowatt/commit/fb7763712935dffa7a3e8734d2e04f68eb955a41). Il faut utiliser une clé d'API v5

**Comment by algernon2607** [comment]
Merci pour la réponse.
En fait , dans paramètres -> Appareils , il faut supprimer l'intégration puis la recréer pour activer , je pense, l'Api V5.
Tout fonctionne désormais
