### ISSUE TITLE
Ajout des options de la V5

### ISSUE THREAD

**Issue by McFlyPartages** [kamaradclimber/rte-ecowatt#80]
Salut @kamaradclimber,

Comptes tu mettre a jour ton intégration avec les nouvelles API v5 ?

https://data.rte-france.com/catalog/-/api/doc/user-guide/Ecowatt/4.0

Bonne continuation

Domotiquement

McFly Anthony

**Comment by kamaradclimber** [comment]
Bonjour,
peux tu préciser les nouveautés de la v5 qui manquent actuellement?
Le support de la v5 a été ajouté dans https://github.com/kamaradclimber/rte-ecowatt/releases/tag/0.7.0 mais peut-être manque-t-il une fonctionnalité.

**Comment by McFlyPartages** [comment]
Salut,

Je parle de cela.

```
Vous pouvez depuis le 8 novembre 2023 vous abonner à la nouvelle version de l’API Ecowatt V5 pour récupérer automatiquement l’ensemble des prévisions horaires : les signaux d’alerte (valeurs 1, 2 ou 3) ainsi que les heures Ecowatt vertueuses (valeur 0).
```

En faite j'ai reçu le mail avang hier de RTE et j'ai vu qu'il n'y avait pas eu de mise à jour.

Mais effectivement, l'API V5 est dispo depuis le 8 novembre et tu as fait une mise a jour le 11 donc les nouvelles informations ont du être ajoutées.

Je regarderais après les fêtes.

Désolé, et merci pour ton intégrâtion.

Bonne fetes de fin d'années

**Comment by McFlyPartages** [comment]
Salut,

Je parle de cela.

```
Vous pouvez depuis le 8 novembre 2023 vous abonner à la nouvelle version de l’API Ecowatt V5 pour récupérer automatiquement l’ensemble des prévisions horaires : les signaux d’alerte (valeurs 1, 2 ou 3) ainsi que les heures Ecowatt vertueuses (valeur 0).
```

En faite j'ai reçu le mail avang hier de RTE et j'ai vu qu'il n'y avait pas eu de mise à jour.

Mais effectivement, l'API V5 est dispo depuis le 8 novembre et tu as fait une mise a jour le 11 donc les nouvelles informations ont du être ajoutées.

Je regarderais après les fêtes.

Désolé, et merci pour ton intégrâtion.

Bonne fetes de fin d'années
