### ISSUE TITLE
Entité manquante

### ISSUE THREAD

**Issue by pinpspinps** [kamaradclimber/rte-ecowatt#81]
Bonjour,

J'ai vu sur le forum de HACF qu'il y a une entité Next load sheddings qui indique le prochain évènement de délestage au niveau local.
Chez moi cette entité n’apparait pas.
![image](https://github.com/kamaradclimber/rte-ecowatt/assets/88548939/50987e09-daff-4822-94b0-3fd814a9a56d)

Est-ce que c'est normal ou il y a quelque chose à faire pour l'activer?

En tout cas merci pour le travail que tu a fait.

**Comment by kamaradclimber** [comment]
Hello,

l'entité n'était plus fonctionnelle depuis assez longtemps (cf https://github.com/kamaradclimber/rte-ecowatt/issues/63 et https://github.com/kamaradclimber/rte-ecowatt/issues/75) et je l'ai donc retirée définitivement dans https://github.com/kamaradclimber/rte-ecowatt/releases/tag/0.9.0.
