### ISSUE TITLE
Ne fonctionn plus depuis version Home Assistant 2024.1.5

### ISSUE THREAD

**Issue by yves-jose** [kamaradclimber/rte-ecowatt#82]
Depuis ma monté de version de Home Assistant 
Les sensors restent en mode inconnu.
Trace dans log :
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 256, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rte_ecowatt/__init__.py", line 189, in update_method
    signals = json.loass(body)["signals"]
              ~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

Que faut-il corriger pour redémarrer cette intégration. 
Nota ; je suis sur Nas Synology avec Docker
Merci

**Comment by kamaradclimber** [comment]
Bonjour,

pouvez-vous indiquer le contenu du fichier `/config/.storage/rte_ecowatt` ?

**Comment by yves-jose** [comment]
Bonjour,
j'ai peut-être posté un peu vite (après trois de non fonctionnement)
apparemment tous est redevenu opérationnel, j'ai d'installé et re-installé plusieurs fois l'intégration et depuis hier soir c'est tombé en marche.
je te joint quand même le fichier : 
{
  "version": 1,
  "minor_version": 1,
  "key": "rte_ecowatt",
  "data": {
    "last_update": "2024-01-27T11:49:23.736413",
    "body": "{\"signals\":[{\"GenerationFichier\":\"2024-01-26T23:00:00+01:00\",\"jour\":\"2024-01-27T00:00:00+01:00\",\"dvalue\":1,\"message\":\"Pas d\\u2019alerte.\",\"values\":[{\"pas\":0,\"hvalue\":1},{\"pas\":1,\"hvalue\":1},{\"pas\":2,\"hvalue\":1},{\"pas\":3,\"hvalue\":1},{\"pas\":4,\"hvalue\":1},{\"pas\":5,\"hvalue\":1},{\"pas\":6,\"hvalue\":1},{\"pas\":7,\"hvalue\":1},{\"pas\":8,\"hvalue\":1},{\"pas\":9,\"hvalue\":1},{\"pas\":10,\"hvalue\":1},{\"pas\":11,\"hvalue\":1},{\"pas\":12,\"hvalue\":1},{\"pas\":13,\"hvalue\":1},{\"pas\":14,\"hvalue\":1},{\"pas\":15,\"hvalue\":1},{\"pas\":16,\"hvalue\":1},{\"pas\":17,\"hvalue\":1},{\"pas\":18,\"hvalue\":1},{\"pas\":19,\"hvalue\":1},{\"pas\":20,\"hvalue\":1},{\"pas\":21,\"hvalue\":1},{\"pas\":22,\"hvalue\":1},{\"pas\":23,\"hvalue\":1}]},{\"GenerationFichier\":\"2024-01-26T23:00:00+01:00\",\"jour\":\"2024-01-28T00:00:00+01:00\",\"dvalue\":1,\"message\":\"Pas d\\u2019alerte.\",\"values\":[{\"pas\":0,\"hvalue\":1},{\"pas\":1,\"hvalue\":1},{\"pas\":2,\"hvalue\":1},{\"pas\":3,\"hvalue\":1},{\"pas\":4,\"hvalue\":1},{\"pas\":5,\"hvalue\":1},{\"pas\":6,\"hvalue\":1},{\"pas\":7,\"hvalue\":1},{\"pas\":8,\"hvalue\":1},{\"pas\":9,\"hvalue\":1},{\"pas\":10,\"hvalue\":1},{\"pas\":11,\"hvalue\":1},{\"pas\":12,\"hvalue\":1},{\"pas\":13,\"hvalue\":1},{\"pas\":14,\"hvalue\":1},{\"pas\":15,\"hvalue\":1},{\"pas\":16,\"hvalue\":1},{\"pas\":17,\"hvalue\":1},{\"pas\":18,\"hvalue\":1},{\"pas\":19,\"hvalue\":1},{\"pas\":20,\"hvalue\":1},{\"pas\":21,\"hvalue\":1},{\"pas\":22,\"hvalue\":1},{\"pas\":23,\"hvalue\":1}]},{\"GenerationFichier\":\"2024-01-26T23:00:00+01:00\",\"jour\":\"2024-01-29T00:00:00+01:00\",\"dvalue\":1,\"message\":\"Pas d\\u2019alerte.\",\"values\":[{\"pas\":0,\"hvalue\":1},{\"pas\":1,\"hvalue\":1},{\"pas\":2,\"hvalue\":1},{\"pas\":3,\"hvalue\":1},{\"pas\":4,\"hvalue\":1},{\"pas\":5,\"hvalue\":1},{\"pas\":6,\"hvalue\":1},{\"pas\":7,\"hvalue\":1},{\"pas\":8,\"hvalue\":1},{\"pas\":9,\"hvalue\":1},{\"pas\":10,\"hvalue\":1},{\"pas\":11,\"hvalue\":1},{\"pas\":12,\"hvalue\":1},{\"pas\":13,\"hvalue\":1},{\"pas\":14,\"hvalue\":1},{\"pas\":15,\"hvalue\":1},{\"pas\":16,\"hvalue\":1},{\"pas\":17,\"hvalue\":1},{\"pas\":18,\"hvalue\":1},{\"pas\":19,\"hvalue\":1},{\"pas\":20,\"hvalue\":1},{\"pas\":21,\"hvalue\":1},{\"pas\":22,\"hvalue\":1},{\"pas\":23,\"hvalue\":1}]},{\"GenerationFichier\":\"2024-01-26T23:00:00+01:00\",\"jour\":\"2024-01-30T00:00:00+01:00\",\"dvalue\":1,\"message\":\"Pas d\\u2019alerte.\",\"values\":[{\"pas\":0,\"hvalue\":1},{\"pas\":1,\"hvalue\":1},{\"pas\":2,\"hvalue\":1},{\"pas\":3,\"hvalue\":1},{\"pas\":4,\"hvalue\":1},{\"pas\":5,\"hvalue\":1},{\"pas\":6,\"hvalue\":1},{\"pas\":7,\"hvalue\":1},{\"pas\":8,\"hvalue\":1},{\"pas\":9,\"hvalue\":1},{\"pas\":10,\"hvalue\":1},{\"pas\":11,\"hvalue\":1},{\"pas\":12,\"hvalue\":1},{\"pas\":13,\"hvalue\":1},{\"pas\":14,\"hvalue\":1},{\"pas\":15,\"hvalue\":1},{\"pas\":16,\"hvalue\":1},{\"pas\":17,\"hvalue\":1},{\"pas\":18,\"hvalue\":1},{\"pas\":19,\"hvalue\":1},{\"pas\":20,\"hvalue\":1},{\"pas\":21,\"hvalue\":1},{\"pas\":22,\"hvalue\":1},{\"pas\":23,\"hvalue\":1}]}]}"
  }
}
Merci pour ton travail.

**Comment by kamaradclimber** [comment]
Merci!
Le fichier a l'air clean mais c'est probablement la version écrite depuis que ca fonctionne à nouveau.
La version https://github.com/kamaradclimber/rte-ecowatt/releases/tag/0.9.1 devrait aider la prochaine fois à avoir plus d'information pour savoir si le problème vient de l'api d'écowatt ou bien du fichier stocké sur disque.

**Comment by kamaradclimber** [comment]
Je ferme le ticket en faveur du #79 qui présente les mêmes symptômes. Merci du rapport !
