### ISSUE TITLE
Compatibility with API v5  ? Status 0 

### ISSUE THREAD

**Issue by Hood-fr** [kamaradclimber/rte-ecowatt#86]
Is the code using API v4 or V5 ? Does the new 0 status can be use in Home Assistant ?
Thanks for the work you did on that integration and thanks for sharing !

**Comment by Ekomak** [comment]
Hi, 
It's not my work, but I checked the prévious relase and found that the code works with V4 and V5 API from EcoWatt since the release [0.7.0 ](https://github.com/kamaradclimber/rte-ecowatt/releases/tag/0.7.0). The link lead to the related changelog.

**Comment by kamaradclimber** [comment]
Thanks @Ekomak for giving all these details. 
It’s true, the integration currently supports v4 and v5 and should continue to do this until the v4 is removed at the end of June.
I strongly recommend to migrate to a v5 api key before that date.
